---
federation:
  inbound:
    service-id-mapping:
    - from: "jfrou@*"
      to: "jfrou@01eq3y5pn2jzt47gncgnqyypwv"
    - from: "jfevt@*"
      to: "jfevt@01eq3y5hnxqgg31h9akh941psg"
    - from: "jfmd@*"
      to: "jfmd@01eq3y5qexw7pcpmwpjtdczkzq"
    - from: "jfrt@*"
      to: "jfrt@01eq3y695wyeyk113jwgpm0jmv"
    - from: "jffe@*"
      to: "jffe@000"
licenses:
- server-name: "5e2861d989a3"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \neE1pMHhNbFF5TXpvME5qb3lNaTQxTVRaYUNtbGtPaUF4TVRjMU5qVXhaaTB6WTJGa0xUUTFNRGd0\r\
    \nT1RJMVl5MHhNREJpTmpFM05EQTBNV0lLYjNkdVpYSTZJRU52YlhCaGJua0tjSEp2Y0dWeWRHbGxj\r\
    \nem9nZTMwS2MybG5ibUYwZFhKbE9pQnVkV3hzQ25SeWFXRnNPaUIwY25WbENuUjVjR1U2SUZSU1NV\r\
    \nRk1DblpoYkdsa1JuSnZiVG9nTWpBeU1DMHhNUzB4TWxReU16bzBOam95TWk0MU1UWmFDZz09CiAg\r\
    \nICBzaWduYXR1cmU6IE54ZXZteVM4M0RiZnZZM0Q0TFc4UzFQejlldHlVdUVWUDUzdWhySXlOZGF5\r\
    \nbTc0Y01YWE5SWVpNVWJwY3ZJdE9WTFljeXhxWXNlT3VDNXorMStWQnk2MzVwN2VacFkyNXcxb2R4\r\
    \nZjdnVGlzbjk3SXBNc1d4cSs5aFRCUkM3SnJiZDhYZWdMWFhramNCaENSTXMwS0EyNWhHb0FWTmly\r\
    \nbG5lMlNzaDdPcWpYMnJZMHhLNWVsZ1grcHVZZ21QbElHSHhrVzlEUWJjcmxJYmcremtQUjhid2Rw\r\
    \nWGFla0pJNG9MSDVTOXJsT3BaMDVxankzeXg3TjJqTkdqa0ZXTTJORXZLM1dodTdjL2FtSmN6c0F5\r\
    \nUmRuTkpmbzJrekRQem53UXNMeFJzMkNuMUx2WlVUTjVyVU5zUzc3Nzhua0wxYm1ucHJDTGNodldY\r\
    \nTjBvenBYbFhxclMxdz09CnZlcnNpb246IDEK\r\n"
- server-name: "1be3f57b75a4"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \neE1pMHhNbFF5TXpvME5qb3lNaTQxTVRaYUNtbGtPaUF4TVRjMU5qVXhaaTB6WTJGa0xUUTFNRGd0\r\
    \nT1RJMVl5MHhNREJpTmpFM05EQTBNV0lLYjNkdVpYSTZJRU52YlhCaGJua0tjSEp2Y0dWeWRHbGxj\r\
    \nem9nZTMwS2MybG5ibUYwZFhKbE9pQnVkV3hzQ25SeWFXRnNPaUIwY25WbENuUjVjR1U2SUZSU1NV\r\
    \nRk1DblpoYkdsa1JuSnZiVG9nTWpBeU1DMHhNUzB4TWxReU16bzBOam95TWk0MU1UWmFDZz09CiAg\r\
    \nICBzaWduYXR1cmU6IE54ZXZteVM4M0RiZnZZM0Q0TFc4UzFQejlldHlVdUVWUDUzdWhySXlOZGF5\r\
    \nbTc0Y01YWE5SWVpNVWJwY3ZJdE9WTFljeXhxWXNlT3VDNXorMStWQnk2MzVwN2VacFkyNXcxb2R4\r\
    \nZjdnVGlzbjk3SXBNc1d4cSs5aFRCUkM3SnJiZDhYZWdMWFhramNCaENSTXMwS0EyNWhHb0FWTmly\r\
    \nbG5lMlNzaDdPcWpYMnJZMHhLNWVsZ1grcHVZZ21QbElHSHhrVzlEUWJjcmxJYmcremtQUjhid2Rw\r\
    \nWGFla0pJNG9MSDVTOXJsT3BaMDVxankzeXg3TjJqTkdqa0ZXTTJORXZLM1dodTdjL2FtSmN6c0F5\r\
    \nUmRuTkpmbzJrekRQem53UXNMeFJzMkNuMUx2WlVUTjVyVU5zUzc3Nzhua0wxYm1ucHJDTGNodldY\r\
    \nTjBvenBYbFhxclMxdz09CnZlcnNpb246IDEK\r\n"
- server-name: "3940d201110f"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \neE1pMHhNbFF5TXpvME5qb3lNaTQxTVRaYUNtbGtPaUF4TVRjMU5qVXhaaTB6WTJGa0xUUTFNRGd0\r\
    \nT1RJMVl5MHhNREJpTmpFM05EQTBNV0lLYjNkdVpYSTZJRU52YlhCaGJua0tjSEp2Y0dWeWRHbGxj\r\
    \nem9nZTMwS2MybG5ibUYwZFhKbE9pQnVkV3hzQ25SeWFXRnNPaUIwY25WbENuUjVjR1U2SUZSU1NV\r\
    \nRk1DblpoYkdsa1JuSnZiVG9nTWpBeU1DMHhNUzB4TWxReU16bzBOam95TWk0MU1UWmFDZz09CiAg\r\
    \nICBzaWduYXR1cmU6IE54ZXZteVM4M0RiZnZZM0Q0TFc4UzFQejlldHlVdUVWUDUzdWhySXlOZGF5\r\
    \nbTc0Y01YWE5SWVpNVWJwY3ZJdE9WTFljeXhxWXNlT3VDNXorMStWQnk2MzVwN2VacFkyNXcxb2R4\r\
    \nZjdnVGlzbjk3SXBNc1d4cSs5aFRCUkM3SnJiZDhYZWdMWFhramNCaENSTXMwS0EyNWhHb0FWTmly\r\
    \nbG5lMlNzaDdPcWpYMnJZMHhLNWVsZ1grcHVZZ21QbElHSHhrVzlEUWJjcmxJYmcremtQUjhid2Rw\r\
    \nWGFla0pJNG9MSDVTOXJsT3BaMDVxankzeXg3TjJqTkdqa0ZXTTJORXZLM1dodTdjL2FtSmN6c0F5\r\
    \nUmRuTkpmbzJrekRQem53UXNMeFJzMkNuMUx2WlVUTjVyVU5zUzc3Nzhua0wxYm1ucHJDTGNodldY\r\
    \nTjBvenBYbFhxclMxdz09CnZlcnNpb246IDEK\r\n"
- server-name: "88c621a0c1d7"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \neE1pMHhNbFF5TXpvME5qb3lNaTQxTVRaYUNtbGtPaUF4TVRjMU5qVXhaaTB6WTJGa0xUUTFNRGd0\r\
    \nT1RJMVl5MHhNREJpTmpFM05EQTBNV0lLYjNkdVpYSTZJRU52YlhCaGJua0tjSEp2Y0dWeWRHbGxj\r\
    \nem9nZTMwS2MybG5ibUYwZFhKbE9pQnVkV3hzQ25SeWFXRnNPaUIwY25WbENuUjVjR1U2SUZSU1NV\r\
    \nRk1DblpoYkdsa1JuSnZiVG9nTWpBeU1DMHhNUzB4TWxReU16bzBOam95TWk0MU1UWmFDZz09CiAg\r\
    \nICBzaWduYXR1cmU6IE54ZXZteVM4M0RiZnZZM0Q0TFc4UzFQejlldHlVdUVWUDUzdWhySXlOZGF5\r\
    \nbTc0Y01YWE5SWVpNVWJwY3ZJdE9WTFljeXhxWXNlT3VDNXorMStWQnk2MzVwN2VacFkyNXcxb2R4\r\
    \nZjdnVGlzbjk3SXBNc1d4cSs5aFRCUkM3SnJiZDhYZWdMWFhramNCaENSTXMwS0EyNWhHb0FWTmly\r\
    \nbG5lMlNzaDdPcWpYMnJZMHhLNWVsZ1grcHVZZ21QbElHSHhrVzlEUWJjcmxJYmcremtQUjhid2Rw\r\
    \nWGFla0pJNG9MSDVTOXJsT3BaMDVxankzeXg3TjJqTkdqa0ZXTTJORXZLM1dodTdjL2FtSmN6c0F5\r\
    \nUmRuTkpmbzJrekRQem53UXNMeFJzMkNuMUx2WlVUTjVyVU5zUzc3Nzhua0wxYm1ucHJDTGNodldY\r\
    \nTjBvenBYbFhxclMxdz09CnZlcnNpb246IDEK\r\n"
- server-name: "33626d86dcc9"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \neE1pMHhNbFF5TXpvME5qb3lNaTQxTVRaYUNtbGtPaUF4TVRjMU5qVXhaaTB6WTJGa0xUUTFNRGd0\r\
    \nT1RJMVl5MHhNREJpTmpFM05EQTBNV0lLYjNkdVpYSTZJRU52YlhCaGJua0tjSEp2Y0dWeWRHbGxj\r\
    \nem9nZTMwS2MybG5ibUYwZFhKbE9pQnVkV3hzQ25SeWFXRnNPaUIwY25WbENuUjVjR1U2SUZSU1NV\r\
    \nRk1DblpoYkdsa1JuSnZiVG9nTWpBeU1DMHhNUzB4TWxReU16bzBOam95TWk0MU1UWmFDZz09CiAg\r\
    \nICBzaWduYXR1cmU6IE54ZXZteVM4M0RiZnZZM0Q0TFc4UzFQejlldHlVdUVWUDUzdWhySXlOZGF5\r\
    \nbTc0Y01YWE5SWVpNVWJwY3ZJdE9WTFljeXhxWXNlT3VDNXorMStWQnk2MzVwN2VacFkyNXcxb2R4\r\
    \nZjdnVGlzbjk3SXBNc1d4cSs5aFRCUkM3SnJiZDhYZWdMWFhramNCaENSTXMwS0EyNWhHb0FWTmly\r\
    \nbG5lMlNzaDdPcWpYMnJZMHhLNWVsZ1grcHVZZ21QbElHSHhrVzlEUWJjcmxJYmcremtQUjhid2Rw\r\
    \nWGFla0pJNG9MSDVTOXJsT3BaMDVxankzeXg3TjJqTkdqa0ZXTTJORXZLM1dodTdjL2FtSmN6c0F5\r\
    \nUmRuTkpmbzJrekRQem53UXNMeFJzMkNuMUx2WlVUTjVyVU5zUzc3Nzhua0wxYm1ucHJDTGNodldY\r\
    \nTjBvenBYbFhxclMxdz09CnZlcnNpb246IDEK\r\n"
- server-name: "0f2618b9b9d9"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \neE1pMHhNbFF5TXpvME5qb3lNaTQxTVRaYUNtbGtPaUF4TVRjMU5qVXhaaTB6WTJGa0xUUTFNRGd0\r\
    \nT1RJMVl5MHhNREJpTmpFM05EQTBNV0lLYjNkdVpYSTZJRU52YlhCaGJua0tjSEp2Y0dWeWRHbGxj\r\
    \nem9nZTMwS2MybG5ibUYwZFhKbE9pQnVkV3hzQ25SeWFXRnNPaUIwY25WbENuUjVjR1U2SUZSU1NV\r\
    \nRk1DblpoYkdsa1JuSnZiVG9nTWpBeU1DMHhNUzB4TWxReU16bzBOam95TWk0MU1UWmFDZz09CiAg\r\
    \nICBzaWduYXR1cmU6IE54ZXZteVM4M0RiZnZZM0Q0TFc4UzFQejlldHlVdUVWUDUzdWhySXlOZGF5\r\
    \nbTc0Y01YWE5SWVpNVWJwY3ZJdE9WTFljeXhxWXNlT3VDNXorMStWQnk2MzVwN2VacFkyNXcxb2R4\r\
    \nZjdnVGlzbjk3SXBNc1d4cSs5aFRCUkM3SnJiZDhYZWdMWFhramNCaENSTXMwS0EyNWhHb0FWTmly\r\
    \nbG5lMlNzaDdPcWpYMnJZMHhLNWVsZ1grcHVZZ21QbElHSHhrVzlEUWJjcmxJYmcremtQUjhid2Rw\r\
    \nWGFla0pJNG9MSDVTOXJsT3BaMDVxankzeXg3TjJqTkdqa0ZXTTJORXZLM1dodTdjL2FtSmN6c0F5\r\
    \nUmRuTkpmbzJrekRQem53UXNMeFJzMkNuMUx2WlVUTjVyVU5zUzc3Nzhua0wxYm1ucHJDTGNodldY\r\
    \nTjBvenBYbFhxclMxdz09CnZlcnNpb246IDEK\r\n"
- server-name: "2e776a218074"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \neE1pMHhNbFF5TXpvME5qb3lNaTQxTVRaYUNtbGtPaUF4TVRjMU5qVXhaaTB6WTJGa0xUUTFNRGd0\r\
    \nT1RJMVl5MHhNREJpTmpFM05EQTBNV0lLYjNkdVpYSTZJRU52YlhCaGJua0tjSEp2Y0dWeWRHbGxj\r\
    \nem9nZTMwS2MybG5ibUYwZFhKbE9pQnVkV3hzQ25SeWFXRnNPaUIwY25WbENuUjVjR1U2SUZSU1NV\r\
    \nRk1DblpoYkdsa1JuSnZiVG9nTWpBeU1DMHhNUzB4TWxReU16bzBOam95TWk0MU1UWmFDZz09CiAg\r\
    \nICBzaWduYXR1cmU6IE54ZXZteVM4M0RiZnZZM0Q0TFc4UzFQejlldHlVdUVWUDUzdWhySXlOZGF5\r\
    \nbTc0Y01YWE5SWVpNVWJwY3ZJdE9WTFljeXhxWXNlT3VDNXorMStWQnk2MzVwN2VacFkyNXcxb2R4\r\
    \nZjdnVGlzbjk3SXBNc1d4cSs5aFRCUkM3SnJiZDhYZWdMWFhramNCaENSTXMwS0EyNWhHb0FWTmly\r\
    \nbG5lMlNzaDdPcWpYMnJZMHhLNWVsZ1grcHVZZ21QbElHSHhrVzlEUWJjcmxJYmcremtQUjhid2Rw\r\
    \nWGFla0pJNG9MSDVTOXJsT3BaMDVxankzeXg3TjJqTkdqa0ZXTTJORXZLM1dodTdjL2FtSmN6c0F5\r\
    \nUmRuTkpmbzJrekRQem53UXNMeFJzMkNuMUx2WlVUTjVyVU5zUzc3Nzhua0wxYm1ucHJDTGNodldY\r\
    \nTjBvenBYbFhxclMxdz09CnZlcnNpb246IDEK\r\n"
- server-name: "e71ad894b59c"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \neE1pMHhNbFF5TXpvME5qb3lNaTQxTVRaYUNtbGtPaUF4TVRjMU5qVXhaaTB6WTJGa0xUUTFNRGd0\r\
    \nT1RJMVl5MHhNREJpTmpFM05EQTBNV0lLYjNkdVpYSTZJRU52YlhCaGJua0tjSEp2Y0dWeWRHbGxj\r\
    \nem9nZTMwS2MybG5ibUYwZFhKbE9pQnVkV3hzQ25SeWFXRnNPaUIwY25WbENuUjVjR1U2SUZSU1NV\r\
    \nRk1DblpoYkdsa1JuSnZiVG9nTWpBeU1DMHhNUzB4TWxReU16bzBOam95TWk0MU1UWmFDZz09CiAg\r\
    \nICBzaWduYXR1cmU6IE54ZXZteVM4M0RiZnZZM0Q0TFc4UzFQejlldHlVdUVWUDUzdWhySXlOZGF5\r\
    \nbTc0Y01YWE5SWVpNVWJwY3ZJdE9WTFljeXhxWXNlT3VDNXorMStWQnk2MzVwN2VacFkyNXcxb2R4\r\
    \nZjdnVGlzbjk3SXBNc1d4cSs5aFRCUkM3SnJiZDhYZWdMWFhramNCaENSTXMwS0EyNWhHb0FWTmly\r\
    \nbG5lMlNzaDdPcWpYMnJZMHhLNWVsZ1grcHVZZ21QbElHSHhrVzlEUWJjcmxJYmcremtQUjhid2Rw\r\
    \nWGFla0pJNG9MSDVTOXJsT3BaMDVxankzeXg3TjJqTkdqa0ZXTTJORXZLM1dodTdjL2FtSmN6c0F5\r\
    \nUmRuTkpmbzJrekRQem53UXNMeFJzMkNuMUx2WlVUTjVyVU5zUzc3Nzhua0wxYm1ucHJDTGNodldY\r\
    \nTjBvenBYbFhxclMxdz09CnZlcnNpb246IDEK\r\n"
- server-name: "4a24703a859d"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \neE1pMHhNbFF5TXpvME5qb3lNaTQxTVRaYUNtbGtPaUF4TVRjMU5qVXhaaTB6WTJGa0xUUTFNRGd0\r\
    \nT1RJMVl5MHhNREJpTmpFM05EQTBNV0lLYjNkdVpYSTZJRU52YlhCaGJua0tjSEp2Y0dWeWRHbGxj\r\
    \nem9nZTMwS2MybG5ibUYwZFhKbE9pQnVkV3hzQ25SeWFXRnNPaUIwY25WbENuUjVjR1U2SUZSU1NV\r\
    \nRk1DblpoYkdsa1JuSnZiVG9nTWpBeU1DMHhNUzB4TWxReU16bzBOam95TWk0MU1UWmFDZz09CiAg\r\
    \nICBzaWduYXR1cmU6IE54ZXZteVM4M0RiZnZZM0Q0TFc4UzFQejlldHlVdUVWUDUzdWhySXlOZGF5\r\
    \nbTc0Y01YWE5SWVpNVWJwY3ZJdE9WTFljeXhxWXNlT3VDNXorMStWQnk2MzVwN2VacFkyNXcxb2R4\r\
    \nZjdnVGlzbjk3SXBNc1d4cSs5aFRCUkM3SnJiZDhYZWdMWFhramNCaENSTXMwS0EyNWhHb0FWTmly\r\
    \nbG5lMlNzaDdPcWpYMnJZMHhLNWVsZ1grcHVZZ21QbElHSHhrVzlEUWJjcmxJYmcremtQUjhid2Rw\r\
    \nWGFla0pJNG9MSDVTOXJsT3BaMDVxankzeXg3TjJqTkdqa0ZXTTJORXZLM1dodTdjL2FtSmN6c0F5\r\
    \nUmRuTkpmbzJrekRQem53UXNMeFJzMkNuMUx2WlVUTjVyVU5zUzc3Nzhua0wxYm1ucHJDTGNodldY\r\
    \nTjBvenBYbFhxclMxdz09CnZlcnNpb246IDEK\r\n"
- server-name: "150858721bf6"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \neE1pMHhNbFF5TXpvME5qb3lNaTQxTVRaYUNtbGtPaUF4TVRjMU5qVXhaaTB6WTJGa0xUUTFNRGd0\r\
    \nT1RJMVl5MHhNREJpTmpFM05EQTBNV0lLYjNkdVpYSTZJRU52YlhCaGJua0tjSEp2Y0dWeWRHbGxj\r\
    \nem9nZTMwS2MybG5ibUYwZFhKbE9pQnVkV3hzQ25SeWFXRnNPaUIwY25WbENuUjVjR1U2SUZSU1NV\r\
    \nRk1DblpoYkdsa1JuSnZiVG9nTWpBeU1DMHhNUzB4TWxReU16bzBOam95TWk0MU1UWmFDZz09CiAg\r\
    \nICBzaWduYXR1cmU6IE54ZXZteVM4M0RiZnZZM0Q0TFc4UzFQejlldHlVdUVWUDUzdWhySXlOZGF5\r\
    \nbTc0Y01YWE5SWVpNVWJwY3ZJdE9WTFljeXhxWXNlT3VDNXorMStWQnk2MzVwN2VacFkyNXcxb2R4\r\
    \nZjdnVGlzbjk3SXBNc1d4cSs5aFRCUkM3SnJiZDhYZWdMWFhramNCaENSTXMwS0EyNWhHb0FWTmly\r\
    \nbG5lMlNzaDdPcWpYMnJZMHhLNWVsZ1grcHVZZ21QbElHSHhrVzlEUWJjcmxJYmcremtQUjhid2Rw\r\
    \nWGFla0pJNG9MSDVTOXJsT3BaMDVxankzeXg3TjJqTkdqa0ZXTTJORXZLM1dodTdjL2FtSmN6c0F5\r\
    \nUmRuTkpmbzJrekRQem53UXNMeFJzMkNuMUx2WlVUTjVyVU5zUzc3Nzhua0wxYm1ucHJDTGNodldY\r\
    \nTjBvenBYbFhxclMxdz09CnZlcnNpb246IDEK\r\n"
- server-name: "324aa074fccb"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \neE1pMHhNbFF5TXpvME5qb3lNaTQxTVRaYUNtbGtPaUF4TVRjMU5qVXhaaTB6WTJGa0xUUTFNRGd0\r\
    \nT1RJMVl5MHhNREJpTmpFM05EQTBNV0lLYjNkdVpYSTZJRU52YlhCaGJua0tjSEp2Y0dWeWRHbGxj\r\
    \nem9nZTMwS2MybG5ibUYwZFhKbE9pQnVkV3hzQ25SeWFXRnNPaUIwY25WbENuUjVjR1U2SUZSU1NV\r\
    \nRk1DblpoYkdsa1JuSnZiVG9nTWpBeU1DMHhNUzB4TWxReU16bzBOam95TWk0MU1UWmFDZz09CiAg\r\
    \nICBzaWduYXR1cmU6IE54ZXZteVM4M0RiZnZZM0Q0TFc4UzFQejlldHlVdUVWUDUzdWhySXlOZGF5\r\
    \nbTc0Y01YWE5SWVpNVWJwY3ZJdE9WTFljeXhxWXNlT3VDNXorMStWQnk2MzVwN2VacFkyNXcxb2R4\r\
    \nZjdnVGlzbjk3SXBNc1d4cSs5aFRCUkM3SnJiZDhYZWdMWFhramNCaENSTXMwS0EyNWhHb0FWTmly\r\
    \nbG5lMlNzaDdPcWpYMnJZMHhLNWVsZ1grcHVZZ21QbElHSHhrVzlEUWJjcmxJYmcremtQUjhid2Rw\r\
    \nWGFla0pJNG9MSDVTOXJsT3BaMDVxankzeXg3TjJqTkdqa0ZXTTJORXZLM1dodTdjL2FtSmN6c0F5\r\
    \nUmRuTkpmbzJrekRQem53UXNMeFJzMkNuMUx2WlVUTjVyVU5zUzc3Nzhua0wxYm1ucHJDTGNodldY\r\
    \nTjBvenBYbFhxclMxdz09CnZlcnNpb246IDEK\r\n"
- server-name: "ec36f061170a"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \neE1pMHhNbFF5TXpvME5qb3lNaTQxTVRaYUNtbGtPaUF4TVRjMU5qVXhaaTB6WTJGa0xUUTFNRGd0\r\
    \nT1RJMVl5MHhNREJpTmpFM05EQTBNV0lLYjNkdVpYSTZJRU52YlhCaGJua0tjSEp2Y0dWeWRHbGxj\r\
    \nem9nZTMwS2MybG5ibUYwZFhKbE9pQnVkV3hzQ25SeWFXRnNPaUIwY25WbENuUjVjR1U2SUZSU1NV\r\
    \nRk1DblpoYkdsa1JuSnZiVG9nTWpBeU1DMHhNUzB4TWxReU16bzBOam95TWk0MU1UWmFDZz09CiAg\r\
    \nICBzaWduYXR1cmU6IE54ZXZteVM4M0RiZnZZM0Q0TFc4UzFQejlldHlVdUVWUDUzdWhySXlOZGF5\r\
    \nbTc0Y01YWE5SWVpNVWJwY3ZJdE9WTFljeXhxWXNlT3VDNXorMStWQnk2MzVwN2VacFkyNXcxb2R4\r\
    \nZjdnVGlzbjk3SXBNc1d4cSs5aFRCUkM3SnJiZDhYZWdMWFhramNCaENSTXMwS0EyNWhHb0FWTmly\r\
    \nbG5lMlNzaDdPcWpYMnJZMHhLNWVsZ1grcHVZZ21QbElHSHhrVzlEUWJjcmxJYmcremtQUjhid2Rw\r\
    \nWGFla0pJNG9MSDVTOXJsT3BaMDVxankzeXg3TjJqTkdqa0ZXTTJORXZLM1dodTdjL2FtSmN6c0F5\r\
    \nUmRuTkpmbzJrekRQem53UXNMeFJzMkNuMUx2WlVUTjVyVU5zUzc3Nzhua0wxYm1ucHJDTGNodldY\r\
    \nTjBvenBYbFhxclMxdz09CnZlcnNpb246IDEK\r\n"
- server-name: "ff631fafa278"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \neE1pMHhNbFF5TXpvME5qb3lNaTQxTVRaYUNtbGtPaUF4TVRjMU5qVXhaaTB6WTJGa0xUUTFNRGd0\r\
    \nT1RJMVl5MHhNREJpTmpFM05EQTBNV0lLYjNkdVpYSTZJRU52YlhCaGJua0tjSEp2Y0dWeWRHbGxj\r\
    \nem9nZTMwS2MybG5ibUYwZFhKbE9pQnVkV3hzQ25SeWFXRnNPaUIwY25WbENuUjVjR1U2SUZSU1NV\r\
    \nRk1DblpoYkdsa1JuSnZiVG9nTWpBeU1DMHhNUzB4TWxReU16bzBOam95TWk0MU1UWmFDZz09CiAg\r\
    \nICBzaWduYXR1cmU6IE54ZXZteVM4M0RiZnZZM0Q0TFc4UzFQejlldHlVdUVWUDUzdWhySXlOZGF5\r\
    \nbTc0Y01YWE5SWVpNVWJwY3ZJdE9WTFljeXhxWXNlT3VDNXorMStWQnk2MzVwN2VacFkyNXcxb2R4\r\
    \nZjdnVGlzbjk3SXBNc1d4cSs5aFRCUkM3SnJiZDhYZWdMWFhramNCaENSTXMwS0EyNWhHb0FWTmly\r\
    \nbG5lMlNzaDdPcWpYMnJZMHhLNWVsZ1grcHVZZ21QbElHSHhrVzlEUWJjcmxJYmcremtQUjhid2Rw\r\
    \nWGFla0pJNG9MSDVTOXJsT3BaMDVxankzeXg3TjJqTkdqa0ZXTTJORXZLM1dodTdjL2FtSmN6c0F5\r\
    \nUmRuTkpmbzJrekRQem53UXNMeFJzMkNuMUx2WlVUTjVyVU5zUzc3Nzhua0wxYm1ucHJDTGNodldY\r\
    \nTjBvenBYbFhxclMxdz09CnZlcnNpb246IDEK\r\n"
- server-name: "33e2fd8dd499"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \neE1pMHhNbFF5TXpvME5qb3lNaTQxTVRaYUNtbGtPaUF4TVRjMU5qVXhaaTB6WTJGa0xUUTFNRGd0\r\
    \nT1RJMVl5MHhNREJpTmpFM05EQTBNV0lLYjNkdVpYSTZJRU52YlhCaGJua0tjSEp2Y0dWeWRHbGxj\r\
    \nem9nZTMwS2MybG5ibUYwZFhKbE9pQnVkV3hzQ25SeWFXRnNPaUIwY25WbENuUjVjR1U2SUZSU1NV\r\
    \nRk1DblpoYkdsa1JuSnZiVG9nTWpBeU1DMHhNUzB4TWxReU16bzBOam95TWk0MU1UWmFDZz09CiAg\r\
    \nICBzaWduYXR1cmU6IE54ZXZteVM4M0RiZnZZM0Q0TFc4UzFQejlldHlVdUVWUDUzdWhySXlOZGF5\r\
    \nbTc0Y01YWE5SWVpNVWJwY3ZJdE9WTFljeXhxWXNlT3VDNXorMStWQnk2MzVwN2VacFkyNXcxb2R4\r\
    \nZjdnVGlzbjk3SXBNc1d4cSs5aFRCUkM3SnJiZDhYZWdMWFhramNCaENSTXMwS0EyNWhHb0FWTmly\r\
    \nbG5lMlNzaDdPcWpYMnJZMHhLNWVsZ1grcHVZZ21QbElHSHhrVzlEUWJjcmxJYmcremtQUjhid2Rw\r\
    \nWGFla0pJNG9MSDVTOXJsT3BaMDVxankzeXg3TjJqTkdqa0ZXTTJORXZLM1dodTdjL2FtSmN6c0F5\r\
    \nUmRuTkpmbzJrekRQem53UXNMeFJzMkNuMUx2WlVUTjVyVU5zUzc3Nzhua0wxYm1ucHJDTGNodldY\r\
    \nTjBvenBYbFhxclMxdz09CnZlcnNpb246IDEK\r\n"
- server-name: "2d69a69a5258"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \neE1pMHhNbFF5TXpvME5qb3lNaTQxTVRaYUNtbGtPaUF4TVRjMU5qVXhaaTB6WTJGa0xUUTFNRGd0\r\
    \nT1RJMVl5MHhNREJpTmpFM05EQTBNV0lLYjNkdVpYSTZJRU52YlhCaGJua0tjSEp2Y0dWeWRHbGxj\r\
    \nem9nZTMwS2MybG5ibUYwZFhKbE9pQnVkV3hzQ25SeWFXRnNPaUIwY25WbENuUjVjR1U2SUZSU1NV\r\
    \nRk1DblpoYkdsa1JuSnZiVG9nTWpBeU1DMHhNUzB4TWxReU16bzBOam95TWk0MU1UWmFDZz09CiAg\r\
    \nICBzaWduYXR1cmU6IE54ZXZteVM4M0RiZnZZM0Q0TFc4UzFQejlldHlVdUVWUDUzdWhySXlOZGF5\r\
    \nbTc0Y01YWE5SWVpNVWJwY3ZJdE9WTFljeXhxWXNlT3VDNXorMStWQnk2MzVwN2VacFkyNXcxb2R4\r\
    \nZjdnVGlzbjk3SXBNc1d4cSs5aFRCUkM3SnJiZDhYZWdMWFhramNCaENSTXMwS0EyNWhHb0FWTmly\r\
    \nbG5lMlNzaDdPcWpYMnJZMHhLNWVsZ1grcHVZZ21QbElHSHhrVzlEUWJjcmxJYmcremtQUjhid2Rw\r\
    \nWGFla0pJNG9MSDVTOXJsT3BaMDVxankzeXg3TjJqTkdqa0ZXTTJORXZLM1dodTdjL2FtSmN6c0F5\r\
    \nUmRuTkpmbzJrekRQem53UXNMeFJzMkNuMUx2WlVUTjVyVU5zUzc3Nzhua0wxYm1ucHJDTGNodldY\r\
    \nTjBvenBYbFhxclMxdz09CnZlcnNpb246IDEK\r\n"
- server-name: "24592ed5cdad"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \neE1pMHhNbFF5TXpvME5qb3lNaTQxTVRaYUNtbGtPaUF4TVRjMU5qVXhaaTB6WTJGa0xUUTFNRGd0\r\
    \nT1RJMVl5MHhNREJpTmpFM05EQTBNV0lLYjNkdVpYSTZJRU52YlhCaGJua0tjSEp2Y0dWeWRHbGxj\r\
    \nem9nZTMwS2MybG5ibUYwZFhKbE9pQnVkV3hzQ25SeWFXRnNPaUIwY25WbENuUjVjR1U2SUZSU1NV\r\
    \nRk1DblpoYkdsa1JuSnZiVG9nTWpBeU1DMHhNUzB4TWxReU16bzBOam95TWk0MU1UWmFDZz09CiAg\r\
    \nICBzaWduYXR1cmU6IE54ZXZteVM4M0RiZnZZM0Q0TFc4UzFQejlldHlVdUVWUDUzdWhySXlOZGF5\r\
    \nbTc0Y01YWE5SWVpNVWJwY3ZJdE9WTFljeXhxWXNlT3VDNXorMStWQnk2MzVwN2VacFkyNXcxb2R4\r\
    \nZjdnVGlzbjk3SXBNc1d4cSs5aFRCUkM3SnJiZDhYZWdMWFhramNCaENSTXMwS0EyNWhHb0FWTmly\r\
    \nbG5lMlNzaDdPcWpYMnJZMHhLNWVsZ1grcHVZZ21QbElHSHhrVzlEUWJjcmxJYmcremtQUjhid2Rw\r\
    \nWGFla0pJNG9MSDVTOXJsT3BaMDVxankzeXg3TjJqTkdqa0ZXTTJORXZLM1dodTdjL2FtSmN6c0F5\r\
    \nUmRuTkpmbzJrekRQem53UXNMeFJzMkNuMUx2WlVUTjVyVU5zUzc3Nzhua0wxYm1ucHJDTGNodldY\r\
    \nTjBvenBYbFhxclMxdz09CnZlcnNpb246IDEK\r\n"
- server-name: "961ed6dd0d5c"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \neE1pMHhNbFF5TXpvME5qb3lNaTQxTVRaYUNtbGtPaUF4TVRjMU5qVXhaaTB6WTJGa0xUUTFNRGd0\r\
    \nT1RJMVl5MHhNREJpTmpFM05EQTBNV0lLYjNkdVpYSTZJRU52YlhCaGJua0tjSEp2Y0dWeWRHbGxj\r\
    \nem9nZTMwS2MybG5ibUYwZFhKbE9pQnVkV3hzQ25SeWFXRnNPaUIwY25WbENuUjVjR1U2SUZSU1NV\r\
    \nRk1DblpoYkdsa1JuSnZiVG9nTWpBeU1DMHhNUzB4TWxReU16bzBOam95TWk0MU1UWmFDZz09CiAg\r\
    \nICBzaWduYXR1cmU6IE54ZXZteVM4M0RiZnZZM0Q0TFc4UzFQejlldHlVdUVWUDUzdWhySXlOZGF5\r\
    \nbTc0Y01YWE5SWVpNVWJwY3ZJdE9WTFljeXhxWXNlT3VDNXorMStWQnk2MzVwN2VacFkyNXcxb2R4\r\
    \nZjdnVGlzbjk3SXBNc1d4cSs5aFRCUkM3SnJiZDhYZWdMWFhramNCaENSTXMwS0EyNWhHb0FWTmly\r\
    \nbG5lMlNzaDdPcWpYMnJZMHhLNWVsZ1grcHVZZ21QbElHSHhrVzlEUWJjcmxJYmcremtQUjhid2Rw\r\
    \nWGFla0pJNG9MSDVTOXJsT3BaMDVxankzeXg3TjJqTkdqa0ZXTTJORXZLM1dodTdjL2FtSmN6c0F5\r\
    \nUmRuTkpmbzJrekRQem53UXNMeFJzMkNuMUx2WlVUTjVyVU5zUzc3Nzhua0wxYm1ucHJDTGNodldY\r\
    \nTjBvenBYbFhxclMxdz09CnZlcnNpb246IDEK\r\n"
schema-version: 2
